// Generated by Xata Codegen 0.21.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "experience",
    columns: [
      { name: "company_name", type: "string" },
      { name: "missions", type: "multiple" },
      { name: "start", type: "string" },
      { name: "end", type: "string" },
      { name: "logo", type: "string" },
      { name: "url", type: "string" },
      { name: "stack", type: "multiple" },
    ],
  },
  {
    name: "projects",
    columns: [
      { name: "name", type: "string" },
      { name: "url", type: "string" },
      { name: "description", type: "text" },
      { name: "logo_url", type: "string" },
      { name: "stack", type: "multiple" },
      { name: "display_order", type: "int", unique: true },
    ],
  },
  {
    name: "socials",
    columns: [
      { name: "social_name", type: "string" },
      { name: "social_link", type: "string" },
    ],
  },
  {
    name: "education",
    columns: [
      { name: "title", type: "string" },
      { name: "dates", type: "string" },
      { name: "school", type: "string" },
      { name: "description", type: "multiple" },
    ],
  },
  { name: "stack", columns: [{ name: "technology_name", type: "string" }] },
  {
    name: "messages",
    columns: [
      { name: "name", type: "string" },
      { name: "company", type: "string" },
      { name: "email", type: "email" },
      { name: "message", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Experience = InferredTypes["experience"];
export type ExperienceRecord = Experience & XataRecord;

export type Projects = InferredTypes["projects"];
export type ProjectsRecord = Projects & XataRecord;

export type Socials = InferredTypes["socials"];
export type SocialsRecord = Socials & XataRecord;

export type Education = InferredTypes["education"];
export type EducationRecord = Education & XataRecord;

export type Stack = InferredTypes["stack"];
export type StackRecord = Stack & XataRecord;

export type Messages = InferredTypes["messages"];
export type MessagesRecord = Messages & XataRecord;

export type DatabaseSchema = {
  experience: ExperienceRecord;
  projects: ProjectsRecord;
  socials: SocialsRecord;
  education: EducationRecord;
  stack: StackRecord;
  messages: MessagesRecord;
};

const SQL_URL = "https://prni80lvo556nd096qb40ordl4.asia-southeast1.xata.tech/sql";

async function runSql(query: string, params: any[] = []) {
  const res = await fetch(SQL_URL, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${process.env.XATA_API_KEY || "xao_5s67BIpcSNKT99A6GpXwZnyw5Nuyy0pR0"}`,
      "Content-Type": "application/json",
      "Connection-String": process.env.DATABASE_URL || "postgresql://xata:rZ1NhQVFF0vg0MiTLdFbzEFdXE4oEuPvZLX7QqWRG3Js6GC8Rn6YDFgFmcfOSkb1@prni80lvo556nd096qb40ordl4.asia-southeast1.xata.tech/xata?sslmode=require"
    },
    body: JSON.stringify({ query, params })
  });
  const data = await res.json();
  return data.rows || [];
}

export const getXataClient = () => {
  return {
    db: {
      projects: {
        getAll: async () => {
          return await runSql("SELECT * FROM projects");
        },
      },
      experience: {
        getAll: async () => {
          return await runSql("SELECT * FROM experience");
        },
      },
      messages: {
        create: async (body: any) => {
          const rows = await runSql(
            `INSERT INTO messages (name, company, email, message) VALUES ($1, $2, $3, $4) RETURNING *`,
            [body.name, body.company, body.email, body.message]
          );
          return rows[0];
        },
      },
    },
  } as any;
};

